- src/ui-kit/experimental/experimental.module.ts
- src/ui-kit/experimental/index.ts
- src/ui-kit/experimental/video-player/index.ts
- src/ui-kit/experimental/video-player/video-player.module.ts
modularizing experimental video component
> [review] Video comp tweak

- src/ui-kit/components/sidenav/services/sidenav.service.ts
found an issue where child items weren't getting removed if a parent was set
> [review] sidenav state fix

- src/ui-kit/elements/button/button.component.ts
Reverts GSA/sam-ui-elements#31
> Revert "[Review] Updating button API"

- src/ui-kit/elements/button/button.component.ts
- src/ui-kit/utilities/deprecator/deprecator.ts
- src/ui-kit/utilities/deprecator/index.ts
- src/ui-kit/utilities/index.ts
Created deprecator class and moved deprecation logic out of button class
> [review] Deprecator

- src/formly/components/autocomplete/autocomplete.component.ts
- src/ui-kit/experimental/button-next/button.module.ts
- src/ui-kit/experimental/button-next/index.ts
- src/ui-kit/experimental/patterns/layout/components/filters-wrapper.component.ts
- src/ui-kit/experimental/patterns/layout/components/layout-components.module.ts
Added a button to sam-filters that only executes updates to the page model when the user clicks run report button
> Form execute button

- src/ui-kit/experimental/experimental.module.ts
- src/ui-kit/experimental/filter-drawer/filter-drawer.component.ts
- src/ui-kit/experimental/filter-drawer/filter-drawer.template.html
- src/ui-kit/experimental/patterns/layout/architecture/model/layout.model.ts
Update filter drawer components to match new designs. Decoupled from page architecture service.
> [review] Filter drawer updates

- src/ui-kit/experimental/actions-list/actions-list.component.ts
- src/ui-kit/experimental/patterns/layout/components/page/page.template.html
- src/ui-kit/experimental/patterns/layout/components/toolbar.component.ts
> [review] toolbar updates

- package.json
Update version with latest changes
> Updated to version 16

- src/ui-kit/experimental/tabs/tabs.component.ts
> [review] resize fix

- test-app/package.json
> vulnerability fix

- src/ui-kit/form-controls/autocomplete-multiselect/autocomplete-multiselect.component.ts
- src/ui-kit/form-controls/autocomplete-multiselect/autocomplete-multiselect.template.html
- src/ui-kit/form-controls/autocomplete/autocomplete.component.ts
- src/ui-kit/form-controls/autocomplete/autocomplete.template.html
- src/ui-kit/wrappers/label-wrapper/label-wrapper.component.ts
- src/ui-kit/wrappers/label-wrapper/label-wrapper.template.html
Swapped logical value to fix bug with label wrapper introduce earlier in the sprint.
> Fixed logic error

- package.json
Updated package.json with newest release version
> Update to version 0.1.0

- package.json
> Update to version 0.1.1

- src/ui-kit/wrappers/fieldset-wrapper/fieldset-wrapper.component.ts
Was giving an issue with the Validation since we did not check if the control was in pristine state or not.
> Check for Validation Errors on FieldSet Wrapper

- src/ui-kit/experimental/patterns/layout/components/feedback-wrapper.component.ts
- src/ui-kit/experimental/patterns/layout/components/index.ts
- src/ui-kit/experimental/patterns/layout/components/layout-components.module.ts
> remove unused component

- src/ui-kit/components/modal/modal.template.html
- duplicate tabindex
- re-arrange content in title to pass IV&V test
> Modal tweak

- src/ui-kit/experimental/patterns/layout/architecture/service/page.service.ts
- src/ui-kit/experimental/patterns/layout/components/aside-toggle.component.ts
- src/ui-kit/experimental/patterns/layout/components/page/page.component.ts
- src/ui-kit/experimental/patterns/layout/components/toolbar.component.ts
- added an observable to the page service that component can optionally subscribe to
- updated page, toggle to interact with service events
> [review] layout updates

- sam-styles/table/_structure.scss
- src/ui-kit/components/data-table/data-table.component.ts
- updating datatable component to support horizontal scrolling via input
> updates for horizontal scroll

- src/ui-kit/components/data-table/data-table.component.ts
small bugfix to toggle hostbinding correctly
> bugfix on datatable horizontal

- src/ui-kit/filters/filters.spec.ts
- test-app/package.json
Creating unit tests for the sam-filters components. Test verify that formly renders the sam ui kit controls.
> Filters testing

- src/ui-kit/experimental/patterns/layout/components/page/page.component.ts
don't make call when service is not present
> bugfix on page next experimental

- src/ui-kit/layout/filters-wrapper/filters-wrapper.component.ts
making button text configurable
> filters wrapper RC tweak

- src/ui-kit/layout/toolbar/aside-toggle.spec.ts
> unit test fix

- src/ui-kit/form-controls/upload-v2/upload-v2.template.html
> upload v2 component - adding label for hidden input

- src/ui-kit/layout/filter-drawer/filter-drawer-chip/filter-drawer-chip.component.ts
fix related to error that came up in the wave 508 tool
> wave 508 fix

- src/ui-kit/form-controls/upload-v2/upload-v2.component.ts
- src/ui-kit/form-controls/upload-v2/upload-v2.template.html
tweak modal to emit on submit only
> tweak modal to emit on submit only

- package.json
Updated version for publishing
> Update package.json to 0.3.8

- src/ui-kit/form-controls/upload-v2/upload-v2.component.ts
- src/ui-kit/form-controls/upload-v2/upload-v2.template.html
adding output emitter for modal open event
> open output for modal on upload v2 component

- package.json
> Updated to 0.4.4

- src/ui-kit/layout/pagination/pagination.component.spec.ts
This is changing fdescribe  to describe  and resolving a path issue.
> resolve path issue and fdescribe

- src/ui-kit/form-templates/international-phone/international.template.html
- src/ui-kit/wrappers/fieldset-wrapper/fieldset-wrapper.template.html
- Moved the required input to the fieldset wrapper so that it wraps the entire module
- ~~Changed the 'required' text from legend to label inside fieldset-wrapper to match other components using label-wrapper.~~
> Some changes to intl phone template

- src/ui-kit/components/comments/comments.template.html
Added missing aria-label on Comment input box
> Fixed missing 508 label issue

- src/ui-kit/form-controls/autocomplete/autocomplete.component.ts
changing debounce time to be configurable
> autucomplete change debounce to input

- package.json
> Updated version to 0.4.5

- .gitignore
Ignoring Sonarqube related files
> Ignore sonarqube

- src/ui-kit/form-controls/upload-v2/upload-v2.spec.ts
> Fix upload component unit tests

- src/ui-kit/components/modal/modal.component.ts
- src/ui-kit/components/modal/modal.template.html
Allows the Disabling of the "Submit" button for the attachments explicit modal use case.
> IAE-12908 

- src/ui-kit/form-controls/text/text.component.ts
the sam-front-end unit tests throw warnings related to this, only unsubscribe if defined
> [review] text component tweak

- src/ui-kit/experimental/experimental.module.ts
Added progress component to experimental module
> Added progress compoennt to experimental module

- src/ui-kit/layout/pagination/pagination.component.ts
> [review] pagination input bugfix

- package.json
> Update to version 0.5.0

- src/ui-kit/layout-deprecated/pages/form-step.component.ts
disable form buttons with component input
> add disabled input to form component

- src/ui-kit/form-controls/date/date.component.ts
IAE-14794 - Best Fit for Listed Ticket. The check does not work as currently expected this should fix it.
Allows "Invalid Date" Error to Appear for Feb 30/31 appose to "Date is a Required Field"
> Minor Check Fix

- src/ui-kit/experimental/dollar/dollar.component.ts
> dollar minor fix

- src/ui-kit/experimental/hierarchical/hierarchical-tree-selectedItem.model.ts
added a update items method in the selected result set
> PR for filter pill changes

- src/ui-kit/experimental/dollar/dollar.component.ts
strToDollar method handling for null cases
> dollar component bugfix

- src/ui-kit/form-controls/radiobutton/radiobutton.template.html
https://cm-jira.usa.gov/browse/IAE-15487
> [Ready for Review]: IAE-15487 Fix JAWS 508 issue with radio buttons

- src/ui-kit/experimental/date-range-v2/date-range-v2.component.ts
sam-ui version 0.8.1 is failing because of disabled is private
> PR for updated disable property as public

- src/ui-kit/components/breadcrumbs/breadcrumbs.template.html
Reverts GSA/sam-ui-elements#272
> Revert "Fix breadcrumbs urlmock accessibility"

- package.json
> Version update0.8.4

- src/ui-kit/components/actions/actions-dropdown/actions-dropdown.component.ts
- src/ui-kit/components/actions/actions-dropdown/actions-dropdown.template.html
Reverts GSA/sam-ui-elements#260
> Revert "adding alt tag for JAWS 17 508 compliance"

- src/ui-kit/form-controls/date/date.component.ts
- src/ui-kit/form-controls/date/date.template.html
Tab changes and get possible number changes
> PR for date key board issue fixes

- src/ui-kit/form-controls/date/date.component.ts
- src/ui-kit/form-controls/date/date.spec.ts
> PR for Date component shift tab issue fix

- src/ui-kit/experimental/hierarchical/hierarchical-tree-grid/hierarchical-tree-grid.component.scss
- src/ui-kit/experimental/hierarchical/hierarchical-tree-grid/hierarchical-tree-grid.component.ts
- src/ui-kit/experimental/hierarchical/hierarchical-tree-header/hierarchical-tree-header.component.ts
- src/ui-kit/experimental/hierarchical/hierarchical-tree/hierarchical-tree.component.ts
- src/ui-kit/experimental/hierarchical/hierarchical/hierarchical.component.html
- src/ui-kit/experimental/hierarchical/hierarchical/hierarchical.component.spec.ts
- src/ui-kit/experimental/hierarchical/hierarchical/hierarchical.component.ts
- src/ui-kit/experimental/hierarchical/selected-result/selected-result.component.html
Add automated release notes package and scripts
Update outdated metadata in package.json
Add pull request template
Add CONTRIBUTING.md with reviewer checklist
Add link to gren instructions in README
> IAE-16242  Fix Browser Compatibility , 508 Issues Hierarchical Component

- .github/PULL_REQUEST_TEMPLATE.md
- .grenrc.json
- CONTRIBUTING.md
- README.md
- package.json
Add automated release notes package and scripts
Update outdated metadata in package.json
Add pull request template
Add CONTRIBUTING.md with reviewer checklist
Add link to gren instructions in README
The goal of this PR is to help improve our overall processes and think about quality when code is first merged into the codebase. We are following several manual processes that are burdensome and time consuming. In addition, we do not have a shared mental model of what a satisfactory code review or satisfactory code means.
This PR does a few things (something we want to move away from...)
1. Add github-release-notes tool dependency and configure it to run with the `npm run release` command in the repo.
* Some local configuration is required, and that is included in updates to the README
* This …
> Add automated release notes, update PR template

- sam-styles/table/_structure.scss
this is a fix for the table headers overlapping
> table overlap fix

- package.json
> upgrade to 0.8.9

- sam-styles/table/_structure.scss
Center up the text on the table headers
IAE-16251
non-breaking change
styles are changed
> Center the text on the table headers

- src/ui-kit/form-controls/date/date.component.ts
- src/ui-kit/form-controls/date/date.spec.ts
> PR for Date related to IAE-16703

- package.json
> IAE-16454 upgrade version to 0.8.10

- src/ui-kit/form-templates/international-phone/index.ts
- src/ui-kit/form-templates/international-phone/international.component.ts
- src/ui-kit/form-templates/international-phone/international.spec.ts
- src/ui-kit/form-templates/international-phone/international.template.html
- src/ui-kit/form-templates/international-phone/sam-extension/extension.component.ts
- src/ui-kit/form-templates/international-phone/sam-extension/extension.spec.ts
- src/ui-kit/form-templates/international-phone/sam-extension/extension.template.html
- src/ui-kit/form-templates/international-phone/sam-extension/index.ts
Added additional input field to the international phone component to accept extensions. This adds to the FormGroup as well.
https://cm-jira.usa.gov/browse/IAE-16693
> IAE 16693 Add  extension input for sam International phone number component

- package.json
Updated the sam-ui-element version to 0.8.11
https://cm-jira.usa.gov/browse/IAE-16457
> IAE-16547 Updated Sam version to 0.8.11

- sam-styles/temp/temp.scss
Added the splash page based on the sketches provided by the designers to the patterns page.
> Splash page

- src/ui-kit/components/alert/alert.template.html
Changed anchor tag to the button
https://cm-jira.usa.gov/browse/IAE-15483#
> IAE-15483 Changed link to button to resolve Jaws issue

- package.json
Update the version of sam-ui-elements from 0.8.11 to 0.8.12
> version update to 0.8.12

- sam-styles/headers/_headers.scss
Changed the style of the accordion for mobile view based on sprint ceremonies feedback
Fixed the padding and background color of the header
IAE-16620 [US] Develop CSS/HTML markup files for SAM Header
> IAE-16620 [US] Develop CSS/HTML markup files for SAM Header

- package.json
> IAE-16462 new sam version release 0.8.13

- package.json
- sam-styles/headers/_headers.scss
Changed the CSS/HTML markup files for SAM Header mobile menu
> IAE-17710 update CSS/HTML markup files for SAM Header mobile menu

- package.json
Updated the version number in package.json to 0.8.14
IAE-16460
CLONE - Publish to github and push code to BSP
> version updated to 0.8.14

- sam-styles/headers/_headers.scss
Resolved padding on the footer issue
> Resolved footer padding issue

- package.json
Updated the version in package.json to 0.8.15
Fixed the padding bug on sam-footer
Used css/html to fix the padding issue on sam-footer
- [x ] Bug fix (non-breaking change which fixes an issue) -> Apply bugfix label
> version update 0.8.15-bug fix

- package.json
> Version 0.8.16

- src/ui-kit/components/actions/actions-dropdown/actions-dropdown.component.ts
- src/ui-kit/components/actions/actions-dropdown/actions-dropdown.template.html
This PR relates to https://github.helix.gsa.gov/GSA-IAE-APPS/sam-front-end/pull/5400 in sam-front-end
https://cm-jira.usa.gov/browse/IAE-16877
> IAE-16877 Update actions-dropdown.template.html to fix a JAWS 508 issue

- package.json
> upgrade version Upgrade to 0.8.17

- sam-styles/icon/_icon.scss
> icons height changed

- src/ui-kit/components/pagination/pagination.template.html
- src/ui-kit/experimental/experimental.module.ts
- src/ui-kit/experimental/sort/index.ts
- src/ui-kit/experimental/sort/sort.component.ts
- src/ui-kit/layout/footer/footer.component.spec.ts
- src/ui-kit/layout/footer/footer.component.ts
- src/ui-kit/layout/footer/footer.module.ts
- src/ui-kit/layout/header/header.component.html
- src/ui-kit/layout/header/header.component.spec.ts
- src/ui-kit/layout/header/header.component.ts
- src/ui-kit/layout/header/header.module.ts
- src/ui-kit/layout/header/top-banner/top-banner.component.spec.ts
- src/ui-kit/layout/header/top-banner/top-banner.component.ts
> Resolving issue with name convention and with extra page items

- src/ui-kit/form-templates/international-phone/international.component.ts
- src/ui-kit/form-templates/international-phone/international.template.html
- src/ui-kit/form-templates/international-phone/number-input-keys.ts
- src/ui-kit/form-templates/international-phone/sam-extension/extension.component.ts
- src/ui-kit/form-templates/international-phone/sam-extension/extension.spec.ts
- src/ui-kit/form-templates/international-phone/sam-extension/extension.template.html
- src/ui-kit/form-templates/international-phone/sam-international-prefix/international-prefix.component.ts
- src/ui-kit/form-templates/international-phone/sam-international-prefix/international-prefix.spec.ts
- src/ui-kit/form-templates/international-phone/sam-international-prefix/international-prefix.template.html
- src/ui-kit/form-templates/international-phone/sam-telephone/telephone.component.ts
- src/ui-kit/form-templates/international-phone/sam-telephone/telephone.template.html
> IAE 17860 validations on international phone component.

- sam-styles/themes/sam-gov.scss
USWDS 1.0 grid is now included in sam-front-end styles.
> Removes USWDS 1.0 grid from sam-styles

- package.json
- src/ui-kit/components/actions/actions-dropdown/actions-dropdown.spec.ts
https://cm-jira.usa.gov/browse/IAE-16467#
> IAE-16467 sam vertion changes to 0.8.20

- package.json
- src/ui-kit/components/actions/actions-dropdown/actions-dropdown.spec.ts
> Sam ui version 0.8.20

- src/ui-kit/components/actions/actions-dropdown/actions-dropdown.spec.ts
Reverts GSA/sam-ui-elements#344
> Revert "Sam ui version 0.8.20"

- package.json
> IAE-16467 Sam ui version 0.8.20

- src/ui-kit/experimental/experimental.module.ts
- src/ui-kit/experimental/pagination/index.ts
- src/ui-kit/experimental/pagination/sds-pagination.component.ts
- src/ui-kit/experimental/pagination/sds-pagination.module.ts
- src/ui-kit/experimental/pagination/sds-pagination.template.html
sds pagination component moved to the experimental template
bug fix for the pagination component
> sds pagination component moved to the experimental template

- src/ui-kit/experimental/video-player/video-player.component.ts
> create toggle functionality for "Access" column for upload-v2

- package.json
> sam version updated to 0.8.21

- src/ui-kit/experimental/pagination/sds-pagination.module.ts
> resolving export and import issue for the pagination module

- src/ui-kit/form-templates/international-phone/international.component.ts
- src/ui-kit/form-templates/international-phone/international.template.html
- src/ui-kit/form-templates/international-phone/sam-extension/extension.component.ts
- src/ui-kit/form-templates/international-phone/sam-extension/extension.template.html
https://cm-jira.usa.gov/browse/IAE-17860
> IAE-17860 extension required validation changes reverted

- sam-styles/table/_structure.scss
https://cm-jira.usa.gov/browse/IAE-17645
> IAE-17645 data-table overflow issue

- src/ui-kit/components/modal/modal.component.ts
- src/ui-kit/components/modal/modal.template.html
> IAE-18570 change for 508 reading

- src/ui-kit/wrappers/fieldset-wrapper/fieldset-wrapper.component.ts
re-adding code that was removed in https://github.com/GSA/sam-ui-elements/commit/187e8e17fa3485447741ca87d664b43c8d63ea98#diff-0ff5338819703c61724d5116ecb2dc98L157
pristine controls shouldn't display errors (and label wrapper still has the same snippet - https://github.com/GSA/sam-ui-elements/blob/master/src/ui-kit/wrappers/label-wrapper/label-wrapper.component.ts#L179)
> fieldset wrapper pristine handling update

- src/ui-kit/wrappers/fieldset-wrapper/fieldset-wrapper.component.ts
Reverts GSA/sam-ui-elements#360
> Revert "fieldset wrapper pristine handling update"

- src/ui-kit/components/modal/modal.component.ts
> focus when no button on modal

- src/ui-kit/components/sidenav/sidenav/sidenav.template.html
We have a icon classes for success, error, pending (blank), but would like to add one for warning too
> sidenav icon class update

- src/ui-kit/form-controls/autocomplete-multiselect/autocomplete-multiselect.component.ts
Running into an issue now where we initialize the form control with an error and dirty status and pass that into the autocomplete component. The label wrapper later on initializes and clears the error. tweak to setup label wrapper after all child components are initialized from the perspective of the autocomplete component. This has been done on other components like the text component where we've seen this issue before.
> autocomplete multiselect label wrapper setup

- src/ui-kit/wrappers/fieldset-wrapper/fieldset-wrapper.component.ts
- src/ui-kit/wrappers/fieldset-wrapper/fieldset-wrapper.template.html
> IAE-14558 add aria label proptery for more/less anchor

- package.json
Update the version of sam-ui-elements to 0.8.29
version update
> version update to 0.8.29

- package.json
> update version to 0.8.30

- sam-styles/card/_card.scss
- sam-styles/search/_search.scss
- sam-styles/statistic/_statistic.scss
- sam-styles/workspace/kpi.scss
- sam-styles/workspace/tier-one.scss
IAE-20497 
workspace dash styles update
update the styles for the workspace dashboard based on the approved designs
IAE-20497
> IAE-20497 - workspace dash styles update

- package.json
- src/ui-kit/form-controls/autocomplete-multiselect/autocomplete-cache.spec.ts
- src/ui-kit/form-controls/autocomplete-multiselect/autocomplete-cache.ts
> IAE-18889 Directory Returning Duplicate Results 

- sam-styles/card/_card.scss
- sam-styles/core/theming/_all-theme.scss
- sam-styles/feed/_feed.scss
- sam-styles/search/_search.scss
- sam-styles/statistic/_statistic.scss
- sam-styles/themes/sam-gov.scss
- sam-styles/utilities/_color.scss
- sam-styles/utilities/_display.scss
- sam-styles/utilities/_flex.scss
- sam-styles/utilities/_padding.scss
- sam-styles/utilities/_text-styles.scss
> Add new utilities to sam-styles

- sam-styles/card/_card.scss
> Add white background

- sam-styles/utilities/_color.scss
> Add background gradient to utilities

- sam-styles/alert/_alert.scss
- sam-styles/button/_button.scss
- sam-styles/card/_card.scss
- sam-styles/sidenav/_structure.scss
- sam-styles/table/_structure.scss
- sam-styles/tag/_tag-outline.scss
- sam-styles/tag/_tag.scss
- sam-styles/utilities/_color.scss
- sam-styles/utilities/_margin.scss
- src/ui-kit/elements/button/button.component.ts
- src/ui-kit/elements/button/button.spec.ts
- src/ui-kit/experimental/alert/alert.component.ts
Created the entity display prototype based off the approved designs given.
IAE-21880
- [ x ] New feature (non-breaking change which adds functionality) -> Apply enhancement label
> Entity display styles

- package.json
version update to 0.9.11
version update to 0.9.11
> version update to 0.9.11

- src/ui-kit/components/sidenav/menu-item/menu-item.component.ts
- src/ui-kit/components/sidenav/menu-item/menu-item.template.html
- src/ui-kit/components/sidenav/sidenav/sidenav.template.html
attr.aria-expanded added to the a tag.
> IAE-22073 aria expanded added to side nav

- package.json
> sam-ui version changes to 0.9.12

- sam-styles/card/_card.scss
- sam-styles/tag/_tag.scss
> styles fix

- sam-styles/table/_structure.scss
- sam-styles/tag/_tag.scss
- sam-styles/utilities/_color.scss
- sam-styles/utilities/_text-styles.scss
> table and contrast fix

- src/ui-kit/form-controls/autocomplete-multiselect/autocomplete-multiselect.component.ts
- src/ui-kit/form-controls/autocomplete-multiselect/autocomplete-multiselect.spec.ts
- src/ui-kit/form-controls/autocomplete/autocomplete.component.ts
> autocomplete multiselect - add clear cache interface + impl

- src/ui-kit/form-controls/autocomplete-multiselect/autocomplete-multiselect.component.ts
- src/ui-kit/form-controls/autocomplete-multiselect/autocomplete-multiselect.spec.ts
- src/ui-kit/form-controls/autocomplete/autocomplete.component.ts
Reverts GSA/sam-ui-elements#387
> Revert "autocomplete multiselect - add clear cache interface + impl"

- src/ui-kit/form-controls/date/date.component.ts
> IAE-21978 Date component error validation changes

- sam-styles/comment/_comment.scss
- sam-styles/themes/sam-gov.scss
- src/ui-kit/components/comments/comment/comment.template.html
- src/ui-kit/components/comments/comments.template.html
> comment max length and text wrapping added

- src/ui-kit/form-controls/autocomplete-multiselect/autocomplete-multiselect.component.ts
- src/ui-kit/form-controls/autocomplete-multiselect/autocomplete-multiselect.spec.ts
- src/ui-kit/form-controls/autocomplete/autocomplete.component.ts
> Autocomplete multi clear cache

- package.json
> version updated to 0.9.14

- src/ui-kit/wrappers/fieldset-wrapper/fieldset-wrapper.component.ts
> IAE-21978 clearing error messages for single control

- package.json
> sam ui version 0.9.15 updated

- src/ui-kit/components/comments/comments.component.ts
> sam-comments max length accessibility fix

- src/ui-kit/components/comments/comments.component.ts
Reverts GSA/sam-ui-elements#395
> Revert "sam-comments max length accessibility fix"

- package.json
- src/ui-kit/components/comments/comments.component.ts
> Federalist build fix and sam version update

- sam-styles/banner/_banner.scss
- src/ui-kit/components/banner/banner.component.ts
- src/ui-kit/components/banner/banner.template.html
> UI update to sam-banner

- src/ui-kit/form-controls/date/date.component.ts
> date validation changes

- src/ui-kit/experimental/hierarchical/autocomplete/autocomplete.component.html
- src/ui-kit/experimental/hierarchical/autocomplete/autocomplete.component.ts
- src/ui-kit/experimental/hierarchical/models/SamHierarchicalAutocompleteConfiguration.ts
- src/ui-kit/experimental/hierarchical/models/SamHierarchicalConfiguration.ts
- src/ui-kit/form-controls/autocomplete-multiselect/autocomplete-multiselect.component.ts
- src/ui-kit/form-controls/autocomplete-multiselect/autocomplete-multiselect.spec.ts
- src/ui-kit/form-controls/autocomplete-multiselect/autocomplete-multiselect.template.html
- src/ui-kit/form-controls/autocomplete/autocomplete.component.ts
- src/ui-kit/form-controls/autocomplete/autocomplete.spec.ts
- src/ui-kit/form-controls/autocomplete/autocomplete.template.html
> adding free text for single autocomplete

- src/ui-kit/components/banner/banner.template.html
> Fix banner AMP issue - id not found/invalid

- package.json
> upgrade to 0.10.0

- src/ui-kit/form-controls/date-range/date-range.component.ts
- src/ui-kit/form-controls/date-range/date-range.template.html
- src/ui-kit/form-controls/date/date.component.ts
- src/ui-kit/form-controls/date/date.template.html
> IAE-23254 Date range focus changes

- package.json
> Remove icons peer dependecy

- src/ui-kit/form-controls/date-range/date-range.component.ts
- src/ui-kit/form-controls/date-range/date-range.template.html
> [Review] Addressing 508 issue for date range unique id issue

- package.json
> sam version updated to 0.11.4

- sam-styles/sidenav/_structure.scss
Focus border added to the sidenav
IAE-22762
> Sidenav focus fix

- sam-styles/statistic/_statistic.scss
Statistics updated to match the new design
IAE-25092
> IAE-25092 - statistics updated

- src/ui-kit/form-controls/sam-sds-autocomplete/autocomplete-search/autocomplete-search.component.html
- src/ui-kit/form-controls/sam-sds-autocomplete/autocomplete-search/autocomplete-search.component.ts
> IAE-25090 aria 1.1

- src/ui-kit/components/sidenav/menu-item/menu-item.component.ts
- src/ui-kit/components/sidenav/menu-item/menu-item.spec.ts
- src/ui-kit/components/sidenav/menu-item/menu-item.template.html
> IAE-23931 Side Nav  aria-expanded with no children

- src/ui-kit/components/modal/modal.component.ts
- src/ui-kit/components/modal/modal.template.html
- src/ui-kit/form-controls/textarea/textarea.component.ts
> IAE-25160 Modal button position and Textarea IE fix revert changes

- sam-styles/button/_button.scss
Icon buttons added to workspace dashboard to match the updated design
IAE-25352
> icon button added

- package.json
> sam-version updated to 0.11.5

- src/ui-kit/form-controls/date/date.component.ts
If control has errors on initialization, fieldset wrapper (child component) doesn't pick it up because it hasn't been initialized yet. Fix is to move wrapper related code into afterviewinit
> fieldset wrapper - move control wrapper updates until afterviewinit

- src/ui-kit/components/modal/index.ts
- src/ui-kit/components/modal/modal.component.ts
- src/ui-kit/components/modal/modal.template.html
modal component was developed before clickoutside directive was created. This led to an implementation where (under a certain modal configuration) click events were previously disabled to prevent the modal from closing when clicking in the main content area. Now that we have a clickoutside directive, we can leverage this instead to properly close the modal if the user clicks in the backdrop area
> modal - update clickoutside behavior

- src/ui-kit/components/modal/index.ts
Upload component double imported a directive in the directives module from last modal update
> modal import update

- src/ui-kit/experimental/dollar/dollar.component.ts
experimental dollar component - firefox emits blur event when it switches from text to number input type, temporarily disabling blur handling
> dollar firefox fix

- src/ui-kit/form-controls/date-range/date-range.component.ts
- src/ui-kit/form-controls/date-time/date-time.component.ts
- src/ui-kit/form-controls/date/date.spec.ts
- src/ui-kit/form-controls/time/time.component.ts
- src/ui-kit/form-controls/time/time.spec.ts
> Fix unrenamed file in sam-date tests

- src/ui-kit/experimental/patterns/layout/components/expansion/expansion-panel.html
> Add aria-label-hidden to sam-expansion-panel (508)

- src/ui-kit/form-controls/autocomplete-multiselect/autocomplete-multiselect.template.html
> L1 autocomplete

- src/ui-kit/form-controls/autocomplete/autocomplete.component.ts
- src/ui-kit/form-controls/autocomplete/autocomplete.spec.ts
inputValue wasn't being cleared and value was re-used for next api call (until user typed into box)
> autocomplete inputValue bugfix

- sam-styles/modal/_modal.scss
- src/ui-kit/components/modal/modal.component.ts
- src/ui-kit/components/modal/modal.template.html
> IAE 25713 Modal condensed white space

- sam-styles/modal/_modal.scss
- src/ui-kit/components/modal/modal.component.ts
- src/ui-kit/components/modal/modal.template.html
> IAE-25713 updated padding issues for the Modal component

- sam-styles/alert/_alert.scss
Exclusions alert styles added to match the updated designs
> Alert styles added

- src/ui-kit/experimental/patterns/layout/components/expansion/accordion-item.ts
> fix(expansion-panel): add default value to expanded input

- src/ui-kit/components/comments/comments.spec.ts
- src/ui-kit/form-controls/date-range/date-range.component.ts
- src/ui-kit/form-controls/date-range/date-range.spec.ts
- src/ui-kit/form-controls/date-range/date-range.template.html
> IAE-26983 Removed Date word from Label.

- package.json
> updated version to 0.11.12

- src/ui-kit/form-controls/sam-sds-autocomplete/autocomplete-search/autocomplete-search.component.html
> made the clear button focusable

- src/ui-kit/components/modal/modal.template.html
- src/ui-kit/form-controls/sam-sds-autocomplete/autocomplete-search/autocomplete-search.component.html
> Stop Chromes autocomplete and set the close button type to button

- src/ui-kit/experimental/patterns/layout/components/expansion/expansion-panel.html
> Fix Tab Order

- package.json
- sam-styles/table/_structure.scss
- src/ui-kit/components/data-table/cell.component.ts
- src/ui-kit/components/data-table/data-table.component.ts
> 0.12.0 beta.0

- src/ui-kit/components/modal/modal.component.ts
- src/ui-kit/components/modal/modal.template.html
- src/ui-kit/form-controls/toggle-switch/toggle-switch.component.ts
- src/ui-kit/form-controls/toggle-switch/toggle-switch.template.html
> JAWS fix for toggle and modal

- src/ui-kit/form-controls/autocomplete/autocomplete.component.ts
- src/ui-kit/form-controls/autocomplete/autocomplete.template.html
> Autocomplete 508 changes

- src/ui-kit/components/pagination/pagination.component.ts
- src/ui-kit/components/pagination/pagination.spec.ts
- src/ui-kit/components/pagination/pagination.template.html
> IAE-23806 Pagination

- src/ui-kit/components/comments/comments.component.ts
- src/ui-kit/components/comments/comments.template.html
- src/ui-kit/form-controls/date-range/date-range.component.ts
https://cm-jira.usa.gov/browse/IAE-24805
> IAE-24805  508 fix for comments and removed Input from Date range labels

- src/ui-kit/components/data-table/sort-header.component.ts
https://cm-jira.usa.gov/browse/IAE-27543
> IAE-27543 Fix for JAWS reading extra text from sam data table header

- src/ui-kit/form-controls/textarea/textarea.component.ts
> textarea ie11 placeholder fix

- package.json
> sam-ui version updated

- src/ui-kit/form-controls/autocomplete/autocomplete.component.ts
fixing undefined issue with viewchild
> ang8 autocomplete viewchild update

- src/ui-kit/form-controls/date-range/date-range.component.ts
> NG8 daterange viewchild fix

- src/ui-kit/components/modal/modal.component.ts
on `openModal()`, modalRoot and modalContent are undefined. Switching static value to fix
> ang8 modal viewchild fixes

- src/ui-kit/form-controls/autocomplete-multiselect/autocomplete-multiselect.component.ts
> NG8 autocomplete multiselect viewchild fix

- src/ui-kit/experimental/hierarchical/hierarchical-tree/hierarchical-tree.component.ts
- src/ui-kit/experimental/patterns/layout/components/expansion/expansion-panel-header.ts
- src/ui-kit/experimental/patterns/layout/components/expansion/expansion-panel.ts
- src/ui-kit/experimental/patterns/layout/components/sidenav/sidenav.ts
- src/ui-kit/experimental/tabs/tab-body.ts
- src/ui-kit/experimental/tabs/tab-group.ts
- src/ui-kit/experimental/tabs/tab-header.ts
- src/ui-kit/experimental/tabs/tab-nav-bar/tab-nav-bar.ts
- src/ui-kit/experimental/tabs/tab.ts
- `Observable.of` no longer works in later versions of rxjs
- `moduleId` property in component metadata has been deprecated and now support seems to be removed (source: https://stackoverflow.com/a/37178295)
> Angular8 cleanup

- src/ui-kit/wrappers/fieldset-wrapper/fieldset-wrapper.component.ts
- src/ui-kit/wrappers/label-wrapper/label-wrapper.component.ts
Hints weren't showing more/less button
> NG8 Wrapper hint fix

- src/ui-kit/form-controls/autocomplete-multiselect/autocomplete-multiselect.component.ts
> Making static as false for resultList to remove console error

- package.json
> Sam-UI Final version for angular-6 to v0.13.0

- src/ui-kit/components/sidenav/sidenav/sidenav.template.html
https://cm-jira.usa.gov/browse/IAE-28216
> sam-sidenav 508 issues

- sam-styles/alert/_alert.scss
> alert link styles

- src/ui-kit/form-controls/date-range/date-range.template.html
- src/ui-kit/form-controls/date/date.component.ts
- src/ui-kit/form-controls/date/date.template.html
> Removed '_' and name changes

- src/ui-kit/form-controls/date/date.component.ts
- src/ui-kit/form-controls/date/date.template.html
> IAE-29041 required label changes

- src/ui-kit/experimental/hierarchical/autocomplete/autocomplete.component.html
- src/ui-kit/form-controls/sam-sds-autocomplete/autocomplete-search/autocomplete-search.component.html
> Autocomplete WAI-ARIA 1.2 changes

- src/ui-kit/form-controls/sam-sds-autocomplete/selected-result/selected-result.component.html
> IAE-29063 Updated aria label for remove item.

- src/ui-kit/components/pagination/pagination.template.html
> fix: add 'page' text to total pages link

- package.json
- src/ui-kit/components/pagination/pagination.spec.ts
- src/ui-kit/experimental/hierarchical/autocomplete/autocomplete.component.ts
> federalist fix and package version updated

- sam-styles/tag/_tag-outline.scss
- sam-styles/tag/_tag.scss
Reverts GSA/sam-ui-elements#490
> Revert "30561 update tags styles"

- package.json
> bump version to v1.0.2

- src/ui-kit/experimental/hierarchical/autocomplete/autocomplete.component.html
- src/ui-kit/form-controls/sam-sds-autocomplete/autocomplete-search/autocomplete-search.component.html
- src/ui-kit/form-controls/sam-sds-autocomplete/autocomplete-search/models/SAMSDSAutocompleteConfiguration.ts
- src/ui-kit/form-controls/sam-sds-autocomplete/autocomplete/models/SDSAutocompletelConfiguration.model.ts
> IAE-31544 Aria Label  configuration changes

- sam-styles/tag/_tag-outline.scss
A small bug was discovered where the status label's dot appear squished when there are long names. this fixes that issue
> Fix Bug with Status Dot

- sam-styles/search/_search.scss
Updated the search icon styles in default and hover states.
IAE SAM/IAE-32613
> Search icon styles update

- src/ui-kit/experimental/hierarchical/autocomplete/autocomplete.component.spec.ts
- src/ui-kit/form-controls/sam-sds-autocomplete/autocomplete-search/autocomplete-search.component.html
- src/ui-kit/form-controls/sam-sds-autocomplete/autocomplete-search/autocomplete-search.component.scss
- src/ui-kit/form-controls/sam-sds-autocomplete/autocomplete-search/autocomplete-search.component.spec.ts
- src/ui-kit/form-controls/sam-sds-autocomplete/autocomplete-search/autocomplete-search.component.ts
- src/ui-kit/form-controls/sam-sds-autocomplete/selected-result/models/sds-selected-item-model-helper.ts
- src/ui-kit/form-controls/sam-sds-autocomplete/selected-result/selected-result.component.spec.ts
> autocomplete-fix

- package.json
> version changes to 1.0.10

- sam-styles/packages/_global.scss
- sam-styles/themes/sam-gov.scss
> fix: fonts and image paths will be handled by SFE

- .circleci/config.yml
- package.json
> Angular 15 upgrade

- package.json
- src/ui-kit/layout/filter-drawer/dynamic-chips/dynamic-chips.directive.ts
> angular 16 changes
