src/ui-kit/utilities/key-helper/key-helper.ts

Duke from REI brought up this bug, peer programmed the fix
bug was that numpad keycodes didn't get picked up in IE11
see chart below for numpad keycodes:
https://www.cambiaresearch.com/articles/15/javascript-char-codes-key-codes

[review] date ie11 keycode fix for numpad

---

sam-styles/table/_theme.scss

setting background color on row instead of button
fixes the below issue

[review] color fix

---

src/ui-kit/components/history/history.component.ts
src/ui-kit/components/history/history.template.html

if ID attribute isn't provided, do not set attribute
fixes an `id="NaN"` value getting assigned if `id` input was not provided

[review] history id attr fix

---

src/ui-kit/form-controls/autocomplete-multiselect/autocomplete-multiselect.component.ts
src/ui-kit/form-controls/autocomplete/autocomplete.component.ts
src/ui-kit/wrappers/label-wrapper/label-wrapper.component.ts
src/ui-kit/wrappers/label-wrapper/label-wrapper.template.html

The last PR had the wrong default value

Inverted hideHint default value

---

src/ui-kit/wrappers/label-wrapper/label-wrapper.template.html

When the toggle-more class was added as a wrapper around the hint container, it wasn't conditional. So a permanent margin for an empty div was added whenever no hint text was supplied. This makes the entire container conditional now, so there is no issue with the margin when no hint is provided.

Fixed alignment bug with label-wrapper CSS

---

src/ui-kit/form-controls/autocomplete/autocomplete.component.ts
src/ui-kit/form-controls/text/text.component.ts

Detaching CDR on destroy for autocomplete. Changed order in sam-text due to reported bug.

Detach cdr on destroy

---

src/ui-kit/form-controls/text/text.component.ts

#Problem:
detectChange() in writeValue()in sam-text is being called after component is destroyed, so it's throwing "ViewDestroyedError" in some fh pages.
#Fix:
added a condition to make sure detectChange() isn't run when the component is destroyed.

Added condition to detectChange on destroyed

---

src/ui-kit/components/multiselect-dropdown/index.ts
src/ui-kit/components/multiselect-dropdown/multiselect-dropdown.component.ts

-minor bug in the label when multiple selections were made
-sam-click-outside directive not working on multiselect-dropdown, hence imported directive into the multiselect-dropdown module
@colinalford @colinalford-gsa

Bug Fix on multiselect-dropdown

---

src/ui-kit/form-controls/upload-v2/upload-v2.template.html
src/ui-kit/types.ts

`UploadedFileData` type has new option `disabled`.
If set to true, attachments will show only their name without a link to download.

Add option to disable attachment url links

---

src/ui-kit/form-controls/upload-v2/upload-v2.component.ts

The upload component is not using the passed in uploaded file data directly,
but creating its own object from it to use internally.
We need to copy over the disabled property.

Fix attachment links not passing disabled property through to template

---

src/ui-kit/components/comments/comment/comment.template.html

momentjs returns "Invalid Date" string when invalid date. If "Invalid Date" is fed into the DatePipe, a javascript error returns. Adding a conditional template update for this case

comment date fix

---

src/ui-kit/components/modal/modal.spec.ts
src/ui-kit/experimental/hierarchical/autocomplete/autocomplete.component.spec.ts
src/ui-kit/form-controls/autocomplete-multiselect/autocomplete-multiselect.spec.ts
src/ui-kit/form-controls/date/date.spec.ts
src/ui-kit/form-controls/time/time.spec.ts
test-app/package.json

Skipped broken unit tests until developers have a chance to fix them. This is so we can get meaninful feedback for new PRs with the CI tool.

Skip Broken Tests

---

src/ui-kit/form-controls/upload-v2/upload-v2.component.ts
src/ui-kit/form-controls/upload-v2/upload-v2.module.ts
src/ui-kit/form-controls/upload-v2/upload-v2.template.html
src/ui-kit/types.ts

Per [IAE-12045](https://cm-jira.usa.gov/browse/IAE-12045),
- Rename "Security" header to "Access"
- Replace secured file checkbox with a toggle (`sam-toggle-switch`)
Per [IAE-12047](https://cm-jira.usa.gov/browse/IAE-12047),
- Add a new modal for when file access is toggled
- Add event emitters for modal open, submit, and close
When toggled, an event is emitted through a new emitter `toggleAccess`.
It is then up to the client to keep track of toggle state.
We do not keep track of the state within upload component at the moment
since we don't use it and `sam-toggle-switch` already handles UI updates.
*Note: Previously we only had one modal (on removing attachments),
so it was named generically e.g. `actionModal`.
Internal references were renamed to be more descriptive e.g. `removeModal`, …

[IAE-12045, IAE-12047] Add file upload secure access toggle

---

src/ui-kit/form-controls/radiobutton/radiobutton.component.ts

Radiobutton component has two different ways of setting
an error message which overwrite each other.
1. In `ngOnInit` by calling `formatErrors` with the associated form control
2. `errorMessage` property passed in the template
If the form control has an error but no `errorMessage` is set,
the error in the form control will be lost and no errors are shown.
Fixed by moving `formatErrors` call into `afterViewInit` phase.

Fix radiobutton error message being overwritten

---

src/ui-kit/form-controls/radiobutton/radiobutton.component.ts

Trying to access `this.control` but radiobutton may be used in a way without any formcontrol.

Fix radiobutton NPE when missing control

---

package.json

Update version. This is being published to fix a bug where an interface needs to be made public instead of private. The PR did not get included in the last version that was published.

Updated to version 0.8.2

---

src/ui-kit/components/breadcrumbs/breadcrumbs.template.html

When we use the `urlmock` option for breadcrumbs, the `<a>` does not have a `href` so it is taken out of the tab order and doesn't have an event handler for enter.
To fix this we need to:
- Add `tabindex` to allow tabbing to the link
- Call click handler on enter keypress as well
Unit tests:

Fix breadcrumbs urlmock accessibility

---

src/ui-kit/components/actions/actions-dropdown/actions-dropdown.component.ts
src/ui-kit/components/actions/actions-dropdown/actions-dropdown.template.html

Adding an "alt" Tag to the sam-actions-dropdown so that we can add specific text to the dropdown if the page we use them on contains multiple for JAWS 508 compliance.

adding alt tag for JAWS 17 508 compliance

---

src/ui-kit/wrappers/label-wrapper/label-wrapper.template.html

Added Aria label for label-wrapper
https://cm-jira.usa.gov/browse/IAE-16714

IAE 16714 Label wrapper "more/less" link accessibility issues 

---

src/ui-kit/form-templates/international-phone/sam-extension/extension.component.ts
src/ui-kit/form-templates/international-phone/sam-international-prefix/international-prefix.component.ts
src/ui-kit/form-templates/international-phone/sam-international-prefix/international-prefix.spec.ts
src/ui-kit/form-templates/international-phone/sam-telephone/telephone.component.ts
src/ui-kit/wrappers/fieldset-wrapper/fieldset-wrapper.component.ts
src/ui-kit/wrappers/fieldset-wrapper/fieldset-wrapper.spec.ts

https://cm-jira.usa.gov/browse/IAE-18688#

IAE-18688 display multiple control validation error messages and extension error msg text change

---

src/ui-kit/form-controls/date/date.component.ts
src/ui-kit/form-controls/date/date.spec.ts

The date component isn't emitting change events if pre-populated, all inputs are pristine, and changing only one field
Current issue:
After fix:

date component - emit event if pristine and inputs already have values

---

src/ui-kit/form-controls/date/date.component.ts

When a user has not added a date, sam-date emits null.
But when a user adds a date then deletes it, sam-date emits Invalid Date.
Sam-date should emit null in both cases to be consistent.
We need to distinguish between invalid date and empty date to determine whether to activate submit button on a date range filter. If start date is valid and end date is empty, user is allowed to filter. But if start date is valid and end date is invalid, user is not allowed to filter.

Allow sam-date to emit null on deleting date

---

sam-styles/input/_input.scss

IAE-27178 add IE css to hide input x

---

src/ui-kit/form-controls/sam-sds-autocomplete/autocomplete-search/autocomplete-search.component.html
src/ui-kit/form-controls/sam-sds-autocomplete/autocomplete-search/autocomplete-search.component.spec.ts
src/ui-kit/form-controls/sam-sds-autocomplete/autocomplete-search/autocomplete-search.component.ts

Resolves two issues - 
1. SDS autocomplete search not making query for additional data once user scrolls to current limit
2. Additional whitespace being created at the bottom of the page as user hovers over autocomplete results

Resolve UI issues with sds-autocomplete component

---

src/ui-kit/form-controls/text/text.component.ts
src/ui-kit/form-controls/text/text.template.html
src/ui-kit/wrappers/label-wrapper/label-wrapper.template.html

1. Adds an additional input to sam text components that allow clients to control display of more / less hint in label wrapper.
2. Adds aria-expanded attribute to more / less link in sam-label-wrapper so that JAWS announces the state of the link (expanded or collapsed)
3. Adds aria-live attribute to the element containing the hint so that the hint is re-read by jaws upon toggling more / less link.
What this change DOES NOT DO:
Jaws will always announce the full hint even if less hint is being displayed. This is because the CSS used to hide the extra text is not removed from DOM, simply hidden from users' sight.
[IAE-28070] - Jaws not announcing state of more / less link
- [ x ] New feature (non-breaking change which adds functionality) -> Apply enhancement label
- [ x ] Chrome
Test status:

Adjust config for sam text and announce wrapper more/less state

---

src/ui-kit/form-controls/checkbox/checkbox.template.html
src/ui-kit/form-controls/radiobutton/radiobutton.template.html
src/ui-kit/form-controls/toggle-switch/toggle-switch.template.html
src/ui-kit/types.ts

This change adds an optional ariaLabel property to OptionsType object that is used to specify what JAWS should announce when focus moves to a radio or checkbox item. Previously we were simply using the visible label passed in as the aria label property of the checkbox or radio. That feature is kept as default if no ariaLabel property is provided. This extends the functionality such that if the clients want some customized screen reader only message instead of the visible label, they may do so. Additionally, it moves the toggleSwitchText input as an aria-label field for toggle switch. Previously, there was a separate sr-only span tag for JAWS to announce description of the toggle switch. However, this was failing 508 check with ANDI as the toggle switch input field itself did not have an …

IAE-38509 & IAE-38521 - allow custom aria label for checkboxes, radio buttons, and toggle switch

---

package.json
src/ui-kit/form-controls/sam-sds-autocomplete/autocomplete/autocomplete.component.ts

The changes here fix issue seen with agency picker in single select mode in sam-front-end3. If the ngModel of the autocomplete is changed from an external component (the agency picker modal in this case), that change was not reflected in the autocomplete input field. This is because the `autocomplete.component.ts` was modifying the model in such a way that the reference to the model itself was not changed. So the internal component - `autocomplete-search.component.ts` would not fire its writeValue method to update the input because the reference to its ngModel was not changed, just the items array in the ngModel object. This change resolves the issue by letting `autocomplete.component.ts` create a new instance of the model object rather than just modifying the items array, which forces …

Resolve single select bug on autocomplete, update package version

---

src/ui-kit/components/modal/modal.component.ts
src/ui-kit/components/modal/modal.template.html

Updates input values for download modal to accept header level. Default header level for dialog title will be h3 if none is provided.
Updates defined id in modal to be dynamic in order to allow multiple modals in the same dom

Resolve amp violation for download modal

---

src/ui-kit/experimental/dollar/dollar.component.ts

The input box is not selected on the first attempt, but it is on the second. Once it is selected, validation is triggered and a warning message is displayed 
moved logic from onFocus to onLooseFocus

reslove validation on focus
